CREATE DATABASE IF NOT EXISTS amazigh_assurances;

CREATE TABLE IF NOT EXISTS t_vol (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	codeClasse VARCHAR(50) DEFAULT NULL,
	codeSousClasse INT(12) DEFAULT NULL,
	formuleVol INT(12) DEFAULT NULL,
	tauxMille DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	montantFranchise DECIMAL(12,2) DEFAULT NULL,
	tauxFranchise DECIMAL(12,2) DEFAULT NULL,
	montant DECIMAL(12,2) DEFAULT NULL,
	formule DECIMAL(12,2) DEFAULT NULL,
	observation VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_vendor (
	id INT(11) NOT NULL AUTO_INCREMENT,
	ville VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_user (
	id INT(11) NOT NULL AUTO_INCREMENT,
	login VARCHAR(50) DEFAULT NULL,
	password VARCHAR(50) DEFAULT NULL,
	profil VARCHAR(50) DEFAULT NULL,
	status INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_usage (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code VARCHAR(10) DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_tierce (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	codeClasse VARCHAR(50) DEFAULT NULL,
	codeSousClasse INT(12) DEFAULT NULL,
	formuleTierce INT(12) DEFAULT NULL,
	primeFixe DECIMAL(12,2) DEFAULT NULL,
	tauxVehiculeNeuf DECIMAL(12,2) DEFAULT NULL,
	majorationRemorque DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	tauxFranchise DECIMAL(12,2) DEFAULT NULL,
	montantFranchise DECIMAL(12,2) DEFAULT NULL,
	observation VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_tarifrc (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeUsage VARCHAR(5) DEFAULT NULL,
	codeClasse INT(12) DEFAULT NULL,
	codeSousClasse INT(12) DEFAULT NULL,
	carburant VARCHAR(20) DEFAULT NULL,
	puissanceFiscale INT(12) DEFAULT NULL,
	nombrePlace INT(9) DEFAULT NULL,
	tonnage DECIMAL(12,2) DEFAULT NULL,
	primeRC DECIMAL(12,2) DEFAULT NULL,
	majorationRemorque DECIMAL(12,2) DEFAULT NULL,
	matiereInflamable DECIMAL(12,2) DEFAULT NULL,
	transportPersonne DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	timbre DECIMAL(12,2) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_tariffrontiere (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(10) DEFAULT NULL,
	codeClasse VARCHAR(10) DEFAULT NULL,
	codeSousClasse INT(12) DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	periode INT(10) DEFAULT NULL,
	typePeriode VARCHAR(20) DEFAULT NULL,
	primeRC DECIMAL(12,2) DEFAULT NULL,
	taxe DECIMAL(12,2) DEFAULT NULL,
	primeDR DECIMAL(12,2) DEFAULT NULL,
	taxeDR DECIMAL(12,2) DEFAULT NULL,
	timbre DECIMAL(12,2) DEFAULT NULL,
	tauxMajoration DECIMAL(12,2) DEFAULT NULL,
	taxeRemorque DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_sousclasse (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(10) DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	codeClasse VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_region (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(12) DEFAULT NULL,
	designation VARCHAR(100) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS t_pta (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeUsage VARCHAR(10) DEFAULT NULL,
	formulePTA INT(12) DEFAULT NULL,
	nombrePlace INT(12) DEFAULT NULL,
	capitalDeces DECIMAL(12,2) DEFAULT NULL,
	capitalInvalidite DECIMAL(12,2) DEFAULT NULL,
	montantFrais DECIMAL(12,2) DEFAULT NULL,
	primeNette DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	accessoirePTA DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_motifretourquittance (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(12) DEFAULT NULL,
	libelle VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_activiteat (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeClasse INT(12) DEFAULT NULL,
	codeActivite INT(12) DEFAULT NULL,
	description VARCHAR(255) DEFAULT NULL,
	taux DECIMAL(12,2) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS t_attestation (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	numeroDebut INT(12) DEFAULT NULL,
	numeroFin INT(12) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	dateReception DATE DEFAULT NULL,
	nombreAttestation INT(12) DEFAULT NULL,
	nombreUtilise INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_banque (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code VARCHAR(50) DEFAULT NULL,
	raisonSociale VARCHAR(255) DEFAULT NULL,
	nomContact VARCHAR(50) DEFAULT NULL,
	tel1 VARCHAR(50) DEFAULT NULL,
	tel2 VARCHAR(50) DEFAULT NULL,
	fax VARCHAR(50) DEFAULT NULL,
	email VARCHAR(255) DEFAULT NULL,
	adresse VARCHAR(255) DEFAULT NULL,
	rue VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_branche (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(10) DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	idCompagnie INT(9) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_classe (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code VARCHAR(50) DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_classeat (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(12) DEFAULT NULL,
	libelle VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_client (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeClient INT(12) DEFAULT NULL,
	typeClient VARCHAR(50) DEFAULT NULL,
	civilite VARCHAR(50) DEFAULT NULL,
	nom VARCHAR(255) DEFAULT NULL,
	adresse VARCHAR(255) DEFAULT NULL,
	rue VARCHAR(100) DEFAULT NULL,
	ville VARCHAR(50) DEFAULT NULL,
	activite VARCHAR(100) DEFAULT NULL,
	email VARCHAR(50) DEFAULT NULL,
	debit DECIMAL(12,2) DEFAULT NULL,
	credit DECIMAL(12,2) DEFAULT NULL,
	tel1 VARCHAR(50) DEFAULT NULL,
	fax VARCHAR(50) DEFAULT NULL,
	permis VARCHAR(50) DEFAULT NULL,
	datePermis DATE DEFAULT NULL,
	tel2 VARCHAR(50) DEFAULT NULL,
	codeRegion INT(12) DEFAULT NULL,
	codeCommercial INT(12) DEFAULT NULL,
	situationFamiliale VARCHAR(50) DEFAULT NULL,
	cin VARCHAR(50) DEFAULT NULL,
	dateNaissance DATE DEFAULT NULL,
	solvabilite INT(12) DEFAULT NULL,
	nombreIncident INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_codereglementsinistre (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(12) DEFAULT NULL,
	libelle VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_commercial (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(12) DEFAULT NULL,
	raisonSocial VARCHAR(255) DEFAULT NULL,
	nomContact VARCHAR(50) DEFAULT NULL,
	Adresse VARCHAR(255) DEFAULT NULL,
	Rue VARCHAR(50) DEFAULT NULL,
	tel1 VARCHAR(50) DEFAULT NULL,
	tel2 VARCHAR(50) DEFAULT NULL,
	email VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_compagnie (
	id INT(11) NOT NULL AUTO_INCREMENT,
	raisonSociale VARCHAR(100) DEFAULT NULL,
	raisonSocialeAbrege VARCHAR(50) DEFAULT NULL,
	codeIntermediaire INT(12) DEFAULT NULL,
	codeMF INT(12) DEFAULT NULL,
	correspondantAuto VARCHAR(50) DEFAULT NULL,
	telCorrespondantAuto VARCHAR(50) DEFAULT NULL,
	correspondantSinistre VARCHAR(50) DEFAULT NULL,
	telCorrespondantSinistre VARCHAR(50) DEFAULT NULL,
	correspondantRecouvrement VARCHAR(50) DEFAULT NULL,
	telCorrespondantRecouvrement VARCHAR(50) DEFAULT NULL,
	adresse VARCHAR(100) DEFAULT NULL,
	rue VARCHAR(50) DEFAULT NULL,
	fax VARCHAR(50) DEFAULT NULL,
	tel VARCHAR(50) DEFAULT NULL,
	email VARCHAR(100) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_defenserecours (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	codeClasse VARCHAR(50) DEFAULT NULL,
	codeSousClasse INT(9) DEFAULT NULL,
	puissanceFiscale INT(9) DEFAULT NULL,
	typeDefense VARCHAR(50) DEFAULT NULL,
	valeurDefense DECIMAL(12,2) DEFAULT NULL,
	formuleDefense INT(12) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_dommagecollision (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(9) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	codeClasse VARCHAR(50) DEFAULT NULL,
	codeSousClasse INT(9) DEFAULT NULL,
	carburant VARCHAR(5) DEFAULT NULL,
	puissanceFiscale INT(12) DEFAULT NULL,
	formuleCollision INT(12) DEFAULT NULL,
	primeFixe DECIMAL(12,2) DEFAULT NULL,
	franchise DECIMAL(12,2) DEFAULT NULL,
	plafond DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	observation VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_expert (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code INT(12) DEFAULT NULL,
	nom VARCHAR(50) DEFAULT NULL,
	adresse VARCHAR(255) DEFAULT NULL,
	ville VARCHAR(50) DEFAULT NULL,
	tel1 VARCHAR(50) DEFAULT NULL,
	tel2 VARCHAR(50) DEFAULT NULL,
	fax VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_fractionprimerc (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	nombreMois INT(12) DEFAULT NULL,
	tauxMois DECIMAL(12,2) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_incendie (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	codeClasse VARCHAR(50) DEFAULT NULL,
	codeSousClasse INT(12) DEFAULT NULL,
	formuleIncendie INT(12) DEFAULT NULL,
	tauxMille DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	designation VARCHAR(255) DEFAULT NULL,
	montantFranchise DECIMAL(12,2) DEFAULT NULL,
	tauxFranchise DECIMAL(12,2) DEFAULT NULL,
	montant DECIMAL(12,2) DEFAULT NULL,
	formule INT(12) DEFAULT NULL,
	observation VARCHAR(255) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS t_individuelconducteur (
	id INT(11) NOT NULL AUTO_INCREMENT,
	codeCompagnie INT(12) DEFAULT NULL,
	codeUsage VARCHAR(50) DEFAULT NULL,
	formuleIndividuel INT(12) DEFAULT NULL,
	capitalDeces DECIMAL(12,2) DEFAULT NULL,
	capitalInvalidite DECIMAL(12,2) DEFAULT NULL,
	montantFrais DECIMAL(12,2) DEFAULT NULL,
	primeNette DECIMAL(12,2) DEFAULT NULL,
	tauxTaxe DECIMAL(12,2) DEFAULT NULL,
	accessoireIndividuel DECIMAL(12,2) DEFAULT NULL,
	tauxCommission DECIMAL(12,2) DEFAULT NULL,
	tauxTPS DECIMAL(12,2) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
